version : "3.8"
networks:
  laravel-network:

services: 
  mysql_ast:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true #enables shell like interface
    ports:
      - "3307:3306"
    
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=123
      - MYSQL_USER=root
      - MYSQL_DATABASE=mysql
      - SERVICE_NAME=mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8091:8091"

  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php-ini/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql_ast
    networks:
      - laravel-network
  
  # myXampp:
  #   container_name: myXampp
  #   image: tomsik68/xampp:8
  #   ports:
  #     - '41061:80'
  #     - '41062:22'
    
  #   volumes: 
  #     - '~my_web_pages:/var/www'
  # volumes:
  #   mysql-data: