version : "3.8"
services: 
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true #enables shell like interface
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=

  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
        - '8080:80'
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./src:/var/www/laravel_docker
      # - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
